### ISSUE TITLE
Dumping Firebase

### ISSUE THREAD

**Issue by jimjones26** [toolset-one/timetracker-one-app#3]
Out of curiosity, would you mind telling me why you dumbed firebase? I have been following along in your development of writer and timetracker and I am interested to hear your reasons, of course if you don't mind. I'm about to implement firebase but my gut is telling me maybe it's not the best way to go.

**Comment by BenKowalski** [comment]
Hello @jimjones26 ,

sorry for not answering faster. I had no eye on the issues and did not think someone's following. I dumped it, for three reasons:

**1. Privacy:** I want my service as free from big tech firms like google, facebook & co as possible. Mainly because of privacy reasons (new version will keep to eu privacy right with servers in germany) and because I think they do a lot of good but also harm the internet seriously.

**2. Speed:** I'm planing some pretty intensive performance features like a service worker which will do the heavy data stuff with indexeddb in it. With firebase, this is not possible. I also had to load several big libraries and I was not able to get the start up time below 400ms. I'd like to reach 100ms for everything.

**3. I had to wrap my head around their concept.** Most of what they do is pretty good and I'll keep firebase for smaller things like the writer app. But when it comes to user management, you have to adopt some weird concepts of them, which are not well documented and not fitting my mindset. Plus, you're not free to adjust some email texts – and so on.

Hope, that this answer helps you.

**Comment by BenKowalski** [comment]
Please feel free to reopen, if there's something missing in this answer. ☺️
